### ISSUE TITLE
Error: Invalid WebSocket frame: RSV1 must be clear

### ISSUE THREAD

**Issue by nguyenhuutuananh** [RFS-ADRENO/zca-js#10]
Hello, I encountered this error message when I tried to run it. I've thoroughly researched the issue, but unfortunately, none of the solutions I've found have resolved it. Additionally, I've tried running the code on a Linux environment (Ubuntu 22.04) using Docker, but the same error persists.

Environments: Macos Sonoma 14.6.1 and Docker in Ubuntu 22.04

The error message:
```INFO zca-js is up to date
INFO Logged in as 77xxxx0528xxxxx733
node:events:497
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: RSV1 must be clear
    at Receiver.getInfo (/Users/user/zalo-bot/lunch-poll-bot/node_modules/ws/lib/receiver.js:209:26)
    at Receiver.startLoop (/Users/user/zalo-bot/lunch-poll-bot/node_modules/ws/lib/receiver.js:155:16)
    at Receiver._write (/Users/user/zalo-bot/lunch-poll-bot/node_modules/ws/lib/receiver.js:94:10)
    at writeOrBuffer (node:internal/streams/writable:564:12)
    at _write (node:internal/streams/writable:493:10)
    at Writable.write (node:internal/streams/writable:502:10)
    at TLSSocket.socketOnData (/Users/user/zalo-bot/lunch-poll-bot/node_modules/ws/lib/websocket.js:1355:35)
    at TLSSocket.emit (node:events:519:28)
    at Readable.read (node:internal/streams/readable:780:10)
    at Socket.read (node:net:772:39)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (/Users/user/zalo-bot/lunch-poll-bot/node_modules/ws/lib/websocket.js:1199:15)
    at Receiver.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'WS_ERR_UNEXPECTED_RSV_1',
  [Symbol(status-code)]: 1002
}

Node.js v20.14.0
```

Could someone help me troubleshoot this error message?

**Comment by RFS-ADRENO** [comment]
Xem thử [comment](https://github.com/websockets/ws/issues/2109#issuecomment-1803625363)
Có lẽ là cùng 1 vấn đề đấy.

**Comment by nguyenhuutuananh** [comment]
@RFS-ADRENO 

Mình đã thử nhưng vẫn không được, code mình hiện tại cũng chỉ dùng từ example chứ chưa chỉnh sửa gì cả. Không biết hiện tại API có đang dùng được không nhỉ? mình đã thử một thư viện dùng Python nhưng cũng không listen message được :(

<img width="822" alt="image" src="https://github.com/user-attachments/assets/4b3f03b3-b736-4fb9-846e-1475b76c27f8">
<img width="714" alt="image" src="https://github.com/user-attachments/assets/ada91239-09a0-4dbb-866b-6f6e1d113857">

**Comment by RFS-ADRENO** [comment]
dùng được b ơi, mình mới chạy thử hồi nãy.
B cho mình xin config docker của b được k?

**Comment by nguyenhuutuananh** [comment]
> dùng được b ơi, mình mới chạy thử hồi nãy. B cho mình xin config docker của b được k?

Đây nha bạn, cũng cơ bản chứ chưa có gì

Dockerfile
```
FROM node:20.17.0-alpine
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY package*.json ./

USER node
RUN npm install
COPY --chown=node:node . .

CMD [ "node", "main.js" ]
```

docker-compose.yml

```
services:
  app:
    build:
      dockerfile: Dockerfile
    environment:
      - ZALO_COOKIE=${ZALO_COOKIE}
      - ZALO_IMEI=${ZALO_IMEI}
      - ZALO_USERAGENT=${ZALO_USERAGENT}
```

**Comment by RFS-ADRENO** [comment]
![image](https://github.com/user-attachments/assets/a11f94d7-55f1-4bef-8292-fdd6287f1a65)

@nguyenhuutuananh, mình đã thử mọi máy rồi, ko thể tái hiện lại lỗi mà bạn gặp.
Mình vừa đẩy bản mới nhất lên, bạn thử cập nhật lên rồi chạy thử xem?

**Comment by nguyenhuutuananh** [comment]
@RFS-ADRENO Mình thử update version và chạy thì lại bị lỗi khác có vẻ liên quan tới thông tin login

<img width="1444" alt="image" src="https://github.com/user-attachments/assets/1a704a1a-08db-4bba-a935-24bbe935f6a0">
<img width="895" alt="image" src="https://github.com/user-attachments/assets/54196af2-30f6-4370-a143-d806d01ce2a0">

**Comment by nguyenhuutuananh** [comment]
@RFS-ADRENO sorry bạn, nảy mình dùng thông tin login từ extension [ZaloDataExtractor](https://github.com/JustKemForFun/ZaloDataExtractor) lại không login được nhưng sau khi dùng Cookie-Editor và lấy uid từ Console thì lại login được nhưng vẫn hiện lỗi giống như cũ :(

<img width="872" alt="image" src="https://github.com/user-attachments/assets/76c5ef5a-a379-4d0f-8a79-0696ce7dde58">
<img width="1130" alt="image" src="https://github.com/user-attachments/assets/244f491e-5436-4502-a63f-6b85e187611b">

**Comment by truong9c2208** [comment]
> Author

bạn ib cho mình coi thử nhé

**Comment by truong9c2208** [comment]
@nguyenhuutuananh bạn ib cho mình coi thử sao nhé

**Comment by JustKemForFun** [comment]
@nguyenhuutuananh bạn cập nhật lên bản mới giúp mình, rồi thử lại có lỗi thì báo lại cho mình với nhe. Cảm ơn nhìu <3

Extension: [here](https://github.com/JustKemForFun/ZaloDataExtractor)

**Comment by nguyenhuutuananh** [comment]
> @nguyenhuutuananh bạn ib cho mình coi thử saosao nhé

mình ib qua đâu đc nhỉ?

**Comment by nguyenhuutuananh** [comment]
> @nguyenhuutuananh bạn cập nhật lên bản mới giúp mình, rồi thử lại có lỗi thì báo lại cho mình với nhe. Cảm ơn nhìu <3
> 
> Extension: [herehere](https://github.com/JustKemForFun/ZaloDataExtractor)

mình có thử lại nhưng vẫn bị lỗi với data nhìn khá lạ. Mình có tạo issue bên repo của extension, bạn xem qua thử

**Comment by truong9c2208** [comment]
> > @nguyenhuutuananh bạn ib cho mình coi thử saosao nhé
> 
> mình ib qua đâu đc nhỉ?

bạn có thể ib qua [Facebook](https://www.facebook.com/shibasama.dev/) hoặc là [Discord](https://discordapp.com/users/847101281277444166) của mình nhé

**Comment by obfuscatus** [comment]
mình cũng đang bị lỗi này, test trên windows và ubuntu desktop ko dùng docker, nodejs version v18.18.0, bản zca 1.4.2

**Comment by truong9c2208** [comment]
> mình cũng đang bị lỗi này, test trên windows và ubuntu desktop ko dùng docker, nodejs version v18.18.0, bản zca 1.4.2

@obfuscatus bạn ib cho mình chi tiết dc ko, tại tụi mình đã test trên rất nhiều máy và hoàn toàn bình thường

**Comment by obfuscatus** [comment]
> > mình cũng đang bị lỗi này, test trên windows và ubuntu desktop ko dùng docker, nodejs version v18.18.0, bản zca 1.4.2
> 
> @obfuscatus bạn ib cho mình chi tiết dc ko, tại tụi mình đã test trên rất nhiều máy và hoàn toàn bình thường


mình đã gửi qua fb

**Comment by nguyenhuutuananh** [comment]
Mình vừa thử lại lấy cookie bằng J2Team Cookies và version 2.0.0-alpha.2 đã chạy được mà chưa rõ lý do, tạm thời mình close issue này.
