### ISSUE TITLE
Không thể gửi kèm ảnh với sendMessage

### ISSUE THREAD

**Issue by vnpresent88** [RFS-ADRENO/zca-js#12]
Như tiêu đề, khi mình đính kèm ả
![image](https://github.com/user-attachments/assets/48fd68af-b159-4523-9009-1cee9e65f9f1)
nh vào attachments để gửi, thì bị lỗi

**Comment by vnpresent88** [comment]
![image](https://github.com/user-attachments/assets/0a9866e9-5f86-4f0b-929d-1858651cf24b)
đây là cách mình dùng sendMessage, cũng là cách này với file txt thì sử dụng bình thường

**Comment by RFS-ADRENO** [comment]
> ![image](https://private-user-images.githubusercontent.com/137747187/371040791-0a9866e9-5f86-4f0b-929d-1858651cf24b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDUxNjMsIm5iZiI6MTcyNzM0NDg2MywicGF0aCI6Ii8xMzc3NDcxODcvMzcxMDQwNzkxLTBhOTg2NmU5LTVmODYtNGYwYi05MjlkLTE4NTg2NTFjZjI0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQxMDAxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjQzZGE5Yzg4NGViYmMwMDVhYmE1YTdhMzY4NTUzMTJlM2I3MTk5NDU3NzhlMmQ0YWI1Y2IzZjY1ZGI0Y2Q1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SCiRKtA224MXuv4Zetg2sR2p8L5-IF_QzY_yZbB6LAY) đây là cách mình dùng sendMessage, cũng là cách này với file txt thì sử dụng bình thường

có thể cho minhf xin cái ảnh của b đc k? Hoặc b thử gửi 1 ảnh nào khác xem

**Comment by vnpresent88** [comment]
![cmt](https://github.com/user-attachments/assets/bdce6e4b-54ce-4296-bdd7-5814d3f0b104)
đây nhé b

**Comment by RFS-ADRENO** [comment]
@vnpresent88  đã fix rồi nha, bạn update lên bản mới nhất nhé

**Comment by vnpresent88** [comment]
cảm ơn bạn
