### ISSUE TITLE
Lấy thông tin người dùng đã nhắn tin

### ISSUE THREAD

**Issue by vnpresent88** [RFS-ADRENO/zca-js#13]
Như tiêu đề, thì mình cần lấy tên + avatar của 1 user đã nhắn tin với mình bằng user_id của user đó nhưng chưa thấy có func hỗ trợ.
Bạn có thể phát triển thêm 1 func giống như getGroupInfo được không nhỉ.
Cảm ơn bạn!

**Comment by RFS-ADRENO** [comment]
ok

**Comment by RFS-ADRENO** [comment]
@vnpresent88 đã thêm api getUserInfo tại 480d9b2d12173256a736730f8e1259850c03b188  rồi nha
Bạn update lên bản mới nhất nhé

**Comment by vnpresent88** [comment]
tuyệt vời bạn ơi
