### ISSUE TITLE
Lấy danh sách group chat người dùng 

### ISSUE THREAD

**Issue by dat2309** [RFS-ADRENO/zca-js#16]
có cách nào để mình có thể lấy danh sách nhóm chat về không

**Comment by RFS-ADRENO** [comment]
theo mình biết thì có nha bạn, tụi mình sẽ xây thêm sau

**Comment by JustKemForFun** [comment]
> có cách nào để mình có thể lấy danh sách nhóm chat về không

mình đang trong quá trình xây bạn nhé vui lòng chờ đợi..

**Comment by JustKemForFun** [comment]
@dat2309 đợi PR (#18) xong update package rồi sử dụng `api.getAllGroups()` để sử dụng nhé

**Comment by dat2309** [comment]
mình cảm ơn nhé

**Comment by JustKemForFun** [comment]
> mình cảm ơn nhé

chỉ có group id thôi bạn nhé còn name group thì kh có..

**Comment by JustKemForFun** [comment]
> mình cảm ơn nhé

nếu không còn gì nữa thì bạn đóng issue #16 giúp mình nhé @dat2309
