### ISSUE TITLE
Lấy thông tin về người dùng giống getGroupInfo

### ISSUE THREAD

**Issue by Rylazius** [RFS-ADRENO/zca-js#17]
Có cách nào để lấy tt về người dùng giống như getGroupInfo ko ạ như kiểu này nè
![image](https://github.com/user-attachments/assets/193fc8d4-90e9-442e-84b3-965e35d94f9f)

**Comment by aftercares0** [comment]
hoặc ko thì có cách nào lấy tt của người dùng (vd tên, av) mình đang nch ko ạ

**Comment by RFS-ADRENO** [comment]
có cái api getUserInfo ấy, mình mới cập nhật gần đây thôi nên chưa update lên document nhma có rồi ấy, bạn sài thử

api.getUserInfo(userId)

**Comment by aftercares0** [comment]
dùng đc r b nhé, thx!
