### ISSUE TITLE
[BUG] Lỗi khi sử dụng zca-js trong nestjs

### ISSUE THREAD

**Issue by lkduy2602** [RFS-ADRENO/zca-js#19]
**Describe the bug**
Khi import { Credentials, Zalo } from 'zca-js'; bị lỗi Error [ERR_REQUIRE_ESM]: require() do thư viện yêu cầu sử dụng "type": "module" nhưng khi build code sang js thì em đang dùng commonjs. Giờ làm sao để fix lỗi này ạ

**Comment by RFS-ADRENO** [comment]
zca hiện tại chưa support cjs, bạn có thể build dự án sang esm hoặc đợi bản cập nhật tiếp theo nha
