### ISSUE TITLE
[Question] how to distinguish between information received 

### ISSUE THREAD

**Issue by truongit2701** [RFS-ADRENO/zca-js#23]
<img width="242" alt="Screenshot 2024-10-31 at 15 33 33" src="https://github.com/user-attachments/assets/d8f36d32-a56c-4d3d-a140-7bd057b992de">
<img width="338" alt="Screenshot 2024-10-31 at 15 33 42" src="https://github.com/user-attachments/assets/4ab0ce94-2c64-45e1-b771-0cb00510e831">

i have two different account connected, but when i send message to personal chat together -> i reiceived 2 response with different uuidFrom, idTo
<img width="259" alt="Screenshot 2024-10-31 at 15 35 51" src="https://github.com/user-attachments/assets/205f3e8f-d2b4-4246-b1a1-39dc2450810f">
<img width="257" alt="Screenshot 2024-10-31 at 15 36 10" src="https://github.com/user-attachments/assets/ed012f8e-f5ac-42df-9e12-065faeea0ee1">
help mee, how to distinguish between information received by the sender to create a personal conversation in my databases

**Comment by hoyen204** [comment]
In the Zalo system, each user has a unique set of IDs for their connections. For example:

- When user A connects with user C, the ID for C from A’s perspective is idCA.
- If user B also connects with C, the ID for C from B’s perspective is idCB.

Thus, the same entity (e.g., user C) cannot share a single ID across multiple accounts; each connection needs its own unique ID.

This is based on my own research and may not be entirely accurate.

**Comment by RFS-ADRENO** [comment]
> In the Zalo system, each user has a unique set of IDs for their connections. For example:
> 
> * When user A connects with user C, the ID for C from A’s perspective is idCA.
> * If user B also connects with C, the ID for C from B’s perspective is idCB.
> 
> Thus, the same entity (e.g., user C) cannot share a single ID across multiple accounts; each connection needs its own unique ID.
> 
> This is based on my own research and may not be entirely accurate.

yes

**Comment by truogvanzz** [comment]
thankss!!!
