### ISSUE TITLE
[Question] Tính năng đăng nhập

### ISSUE THREAD

**Issue by thuysalemall** [RFS-ADRENO/zca-js#29]
Hi, tác giả
- Mình thấy thư viện của bạn rất hay và đúng cái mình cần nhưng nó hiện đang chưa tính năng đăng nhập bằng QR code nếu có thêm nữa thì rất hay, liệu bạn có thể phát triển thêm tính năng này không ạ? 
Xin cảm ơn

**Comment by RFS-ADRENO** [comment]
Đó thật sự là một tính năng hay, để bọn mình nghiên cứu nhé.

**Comment by hoyen204** [comment]
> Đó thật sự là một tính năng hay, để bọn mình nghiên cứu nhé.

Mình đã làm xong bên c# nhưng khi chuyển sang nodejs thì có 1 vài vấn đề về redirect với cookie vẫn chưa xử lí được 😅

**Comment by RFS-ADRENO** [comment]
Đã xong nhé, update bản mới nhất nha
