### ISSUE TITLE
[BUG] Nghe tin nhắn tạo nhắc hẹn

### ISSUE THREAD

**Issue by truongit2701** [RFS-ADRENO/zca-js#31]
**Describe the bug**
Khi mình dùng onMessage tin nhắc hẹn với msgType "chat.ecard" thì thư viện của mình bị lỗi ý. Các bạn có thể kiểm tra và support giúp mình được kh ạ!
Đây là ảnh lỗi mình chụp lại
![Screenshot 2024-11-13 at 14 04 06](https://github.com/user-attachments/assets/d9240141-c1df-4d92-8b36-c8b4731cf006)

**Comment by RFS-ADRENO** [comment]
ok bạn, để nghiên cứu lỗi
