### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by manhict** [RFS-ADRENO/zca-js#33]
version: "zca-js": "^2.0.0-alpha.2"

*** ERROR: fix
import { MD5 } from "crypto-js";
         ^^^
SyntaxError: Named export 'MD5' not found. The requested module 'crypto-js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'crypto-js';
const { MD5 } = pkg;

type: 'module'

**Comment by JustKemForFun** [comment]
hmm, you maybe try to convert line 6 of **package.json** change `module` to `commonjs`

**Comment by manhict** [comment]
Can you fix in npm, src I can't pass to commonjs

**Comment by JustKemForFun** [comment]
@RFS-ADRENO is in charge of building on **npmjs**. Pls wait for him <(‘’)

**Comment by manhict** [comment]
Good, Đã sửa lỗi tự động cập nhật, nhưng sẽ không được lên version mới nhất. Hy vọng sử dụng được version mới nhật ở bản cập nhật mới nhất

**Comment by RFS-ADRENO** [comment]
@manhict cho xem code mẫu mà ô bị lỗi với

**Comment by manhict** [comment]
<img width="1440" alt="Screenshot 2024-12-02 at 22 34 01" src="https://github.com/user-attachments/assets/f3fc3145-5eb3-4086-991e-84a63cc8a327">

@RFS-ADRENO
