### ISSUE TITLE
[Question] Lấy tất cả thông tin của user trong group

### ISSUE THREAD

**Issue by thuytx03** [RFS-ADRENO/zca-js#38]
Hi, tác giả!
Mình đang có 1 case muốn lấy ra thông tin của các thành viên trong group không biết bên bạn có api nào hỗ trợ việc này k ạ.
Xin cảm ơn

**Comment by RFS-ADRENO** [comment]
lấy toàn bộ thì chưa có, bạn có thể kết hợp 2 api là `getGroupInfo` lấy ra id của các thành viên sau đó sử dụng `getUserInfo` để lấy thông tin user

**Comment by thuytx03** [comment]
> lấy toàn bộ thì chưa có, bạn có thể kết hợp 2 api là `getGroupInfo` lấy ra id của các thành viên sau đó sử dụng `getUserInfo` để lấy thông tin user

oki, tkiu @RFS-ADRENO
